name=input("enter name:")
email=input("enter email:")
phone=int(input("enter phone no."))
address=input("enter address:")
print("\n")
print("NAME:",name)
print("EMAIL:",email)
print("PHONE NO.",phone)
print("ADDRESS:",address)
